=== UoS-ECS-AIC-Argumentation/tweetyPrEAF/org-tweetyproject-arg-peaf/src/main/resources/preeaf.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="PrEEAF" type="PrEEAFType">
        <xs:key name="PK_Argument">
            <xs:selector xpath="Argument"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="PK_Support">
            <xs:selector xpath="Support"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="PK_Attack">
            <xs:selector xpath="Attack"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>

    <xs:complexType name="PrEEAFType">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="Argument"/>
            <xs:element ref="Support"/>
            <xs:element ref="Attack"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ArgumentType">
        <xs:sequence minOccurs="0">
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>

    <xs:complexType name="ArgumentGroup">
        <xs:complexContent>
            <xs:extension base="ArgumentType">
                <xs:attribute name="refids" type="xs:IDREFS"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Element">
        <xs:complexContent>
            <xs:extension base="ArgumentType">
                <xs:attribute name="refid" type="xs:IDREF"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Argument" type="ArgumentType"/>

    <xs:element name="Support">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Froms" type="ArgumentGroup" minOccurs="1" maxOccurs="1"/>
                <xs:element name="To" type="Element" minOccurs="1" maxOccurs="1"/>
                <xs:element name="probability" type="xs:double"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Attack">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="From" type="Element" minOccurs="1" maxOccurs="1"/>
                <xs:element name="To" type="Element" minOccurs="1" maxOccurs="1"/>
                <xs:element name="probability" type="xs:double"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== UoS-ECS-AIC-Argumentation/tweetyPrEAF/org-tweetyproject-arg-peaf/src/main/resources/preeaf.xml
<?xml version="1.0" encoding="UTF-8"?>

<PrEEAF xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./preeaf.xsd">

    <Argument id="argument1">
        <name>eta</name>
    </Argument>

    <Argument id="argument2">
        <name>argument2</name>
    </Argument>

    <Argument id="argument3">
        <name>argument3</name>
    </Argument>

    <Support id="support1">
        <Froms refids="argument1 argument3"/>
        <To refid="argument2"/>
        <probability>0.35</probability>
    </Support>

    <Attack id="attack2">
        <From refid="argument2"/>
        <To refid="argument3"/>
        <probability>0.12</probability>
    </Attack>


    <Attack id="attack1">
        <From refid="argument2"/>
        <To refid="attack2"/>
        <probability>0.51</probability>
    </Attack>

</PrEEAF>
